<dec f='include/python3.8/pyerrors.h' l='219' type='PyObject * PyErr_NewExceptionWithDoc(const char * name, const char * doc, PyObject * base, PyObject * dict)'/>
