<dec f='include/python3.8/pyerrors.h' l='89' type='PyObject *'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/internals.h' l='231' u='r' c='_ZN8pybind116detail19translate_exceptionENSt15__exception_ptr13exception_ptrE'/>
