<dec f='include/python3.8/pyerrors.h' l='211' type='void _PyErr_BadInternalCall(const char * filename, int lineno)'/>
