<dec f='llvm/build/projects/compiler-rt/lib/fuzzer/libcxx_fuzzer_x86_64/include/c++/v1/exception' l='114' type='void std::bad_exception::~bad_exception()'/>
<dec f='llvm/build/projects/compiler-rt/lib/fuzzer/libcxx_fuzzer_i386/include/c++/v1/exception' l='114' type='void std::bad_exception::~bad_exception()'/>
<dec f='llvm/build/include/c++/v1/exception' l='114' type='void std::bad_exception::~bad_exception()'/>
<dec f='llvm/libcxx/include/exception' l='114' type='void std::bad_exception::~bad_exception()'/>
<inh f='llvm/libcxxabi/src/stdlib_exception.cpp' l='17' c='_ZNSt9exceptionD1Ev'/>
<def f='llvm/libcxxabi/src/stdlib_exception.cpp' l='28' ll='30' type='void std::bad_exception::~bad_exception()'/>
<doc f='llvm/libcxxabi/src/stdlib_exception.cpp' l='26'>// bad_exception</doc>
