<dec f='include/python3.8/pyerrors.h' l='102' type='PyObject *'/>
<use f='llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp' l='4330' u='r' c='_ZN13PyErr_CleanerD1Ev'/>
