<dec f='include/python3.8/pyerrors.h' l='101' type='PyObject *'/>
<use f='llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp' l='897' u='r' c='_ZL21SWIG_Python_ErrorTypei'/>
<use f='llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp' l='1222' u='r' c='_ZL23SWIG_Python_UnpackTupleP7_objectPKcllPS0_'/>
