<dec f='include/python3.8/pyerrors.h' l='133' type='PyObject *'/>
<use f='llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp' l='873' u='r' c='_ZL21SWIG_Python_ErrorTypei'/>
