<dec f='include/python3.8/pyerrors.h' l='321' type='int PyOS_snprintf(char * str, size_t size, const char * format)'/>
<use f='llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp' l='2507' u='c' c='_ZL19SWIG_Python_ArgFaili'/>
