<inh f='llvm/build/include/c++/v1/exception' l='99' c='std::exception'/>
<def f='llvm/build/include/c++/v1/functional' l='1421' ll='1430'/>
<use f='llvm/build/include/c++/v1/functional' l='1436' c='_ZNSt3__125__throw_bad_function_callEv'/>
<size>8</size>
<doc f='llvm/build/include/c++/v1/functional' l='1415'>////////////////////////////////////////////////////////////////////////////////
//                                FUNCTION
//==============================================================================

// bad_function_call</doc>
<inh f='llvm/libcxx/include/exception' l='99' c='std::exception'/>
<def f='llvm/libcxx/include/functional' l='1421' ll='1430'/>
<use f='llvm/libcxx/include/functional' l='1436' c='_ZNSt3__125__throw_bad_function_callEv'/>
<size>8</size>
<doc f='llvm/libcxx/include/functional' l='1415'>////////////////////////////////////////////////////////////////////////////////
//                                FUNCTION
//==============================================================================

// bad_function_call</doc>
