<dec f='include/python3.8/pyerrors.h' l='39' type='int PyException_SetTraceback(PyObject * , PyObject * )'/>
<doc f='include/python3.8/pyerrors.h' l='38'>/* Traceback manipulation (PEP 3134) */</doc>
<use f='halide/build/_deps/pybind11-src/include/pybind11/cast.h' l='430' u='c' c='_ZN8pybind116detail12error_stringB5cxx11Ev'/>
